# Generated by Django 5.2.2 on 2025-07-05 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postview',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together=set(),
        ),
    ]
